import 'package:flutter_test/flutter_test.dart';
import 'package:rpg/services/encounter_service.dart';

/// Pins the combat curves to `tools/damage_calc.py --model excess
/// --k-max-hit 75`, the tuning tool they were shaped in. Expected values were
/// generated by that script; regenerate them there before changing them here.
void main() {
  final service = EncounterService();

  group('computeMaxHit', () {
    test('matches the tuning tool', () {
      const cases = [
        [1, 1, 1],
        [10, 10, 5],
        [10, 50, 3],
        [50, 10, 15],
        [50, 50, 12],
        [75, 40, 16],
        [100, 100, 16],
        [120, 60, 19],
        [200, 200, 20],
        [200, 50, 27],
        [37, 113, 7],
      ];
      for (final c in cases) {
        expect(
          service.computeMaxHit(attack: c[0], defense: c[1]),
          c[2],
          reason: 'attack ${c[0]} vs defence ${c[1]}',
        );
      }
    });

    test('never drops below 1, even hopelessly outmatched', () {
      expect(service.computeMaxHit(attack: 0, defense: 0), 1);
      expect(service.computeMaxHit(attack: 1, defense: 10000), 1);
    });

    test('rises with attack and falls with defence', () {
      for (var defence = 0; defence <= 300; defence += 25) {
        var previous = 0;
        for (var attack = 1; attack <= 300; attack++) {
          final hit = service.computeMaxHit(attack: attack, defense: defence);
          expect(hit, greaterThanOrEqualTo(previous));
          previous = hit;
        }
      }

      // More defence must never mean a bigger hit -- the artifact that ruled
      // out weakening the below-parity term. See tools/README.md.
      for (var attack = 1; attack <= 400; attack += 7) {
        var previous = 1 << 30;
        for (var defence = 0; defence <= 600; defence++) {
          final hit = service.computeMaxHit(attack: attack, defense: defence);
          expect(
            hit,
            lessThanOrEqualTo(previous),
            reason: 'attack $attack gained max hit at defence $defence',
          );
          previous = hit;
        }
      }
    });

    test('the slope halves once attack passes defence', () {
      // Below parity every point of attack is worth s; above it, s * s.
      const defence = 100;
      final below = service.computeMaxHit(attack: 90, defense: defence) -
          service.computeMaxHit(attack: 40, defense: defence);
      final above = service.computeMaxHit(attack: 200, defense: defence) -
          service.computeMaxHit(attack: 150, defense: defence);
      expect(above, lessThan(below));
    });
  });

  group('chanceToHit', () {
    test('matches the tuning tool', () {
      const cases = [
        [1, 1, 0.9000000000],
        [10, 10, 0.9000000000],
        [10, 50, 0.0770542717],
        [50, 10, 0.9989703535],
        [50, 50, 0.9000000000],
        [75, 40, 0.9877243128],
        [100, 100, 0.9000000000],
        [120, 60, 0.9912274354],
        [200, 200, 0.9000000000],
        [200, 50, 0.9993286879],
        [37, 113, 0.1468795796],
      ];
      for (final c in cases) {
        expect(
          service.chanceToHit(c[0].toInt(), c[1].toInt()),
          closeTo(c[2] as double, 1e-9),
          reason: 'attack ${c[0]} vs defence ${c[1]}',
        );
      }
    });

    test('90% at parity at every level', () {
      for (final level in [1, 5, 20, 60, 99, 250]) {
        expect(
          service.chanceToHit(level, level),
          closeTo(EncounterService.hitChanceAtParity, 1e-12),
        );
      }
    });

    test('stays in range and moves the right way', () {
      for (var defence = 0; defence <= 200; defence += 10) {
        var previous = -1.0;
        for (var attack = 0; attack <= 200; attack += 5) {
          final chance = service.chanceToHit(attack, defence);
          expect(chance, inInclusiveRange(0.0, 1.0));
          expect(chance, greaterThanOrEqualTo(previous));
          previous = chance;
        }
      }
    });

    test('no attack stat lands nothing', () {
      expect(service.chanceToHit(0, 50), 0.0);
    });

    test('one point of attack never doubles your hit chance', () {
      // The swinginess this curve was tuned to remove: without
      // EncounterService.hitChanceFooting a single point is worth up to 16x
      // at the bottom of the range. Worst case with it is ~1.52x.
      for (var defence = 1; defence <= 60; defence++) {
        for (var attack = 1; attack <= 20; attack++) {
          final before = service.chanceToHit(attack, defence);
          final after = service.chanceToHit(attack + 1, defence);
          expect(
            after / before,
            lessThan(2.0),
            reason: 'attack $attack -> ${attack + 1} vs defence $defence',
          );
        }
      }
    });
  });

  test('gathering rolls through the same curve', () {
    // Nodes pass their gathering skill as the attack and the node's
    // difficulty as the defence -- no separate curve.
    expect(service.chanceToHit(10, 10), closeTo(0.9, 1e-12));
    // workable, not hopeless -- the bare ratio would make this 0.09%
    expect(service.chanceToHit(1, 10), closeTo(0.36, 0.01));
  });
}
